export const SERVICE_BASE = {
  cardDetails: {
    ranks: [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25
    ],
    colors: [
      'Red',
      'Green',
      'Yellow',
      'Red',
      'Yellow',
      'Green',
      'Green',
      'Green',
      'Green',
      'Red',
      'Green',
      'Red',
      'Red',
      'Red',
      'Red',
      'Yellow',
      'Yellow',
      'Yellow',
      'Yellow',
      'Yellow',
      'Yellow',
      'Yellow',
      'Green',
      'Green',
      'Green'
    ],
    charges: [
      3,
      2,
      3,
      1,
      1,
      3,
      2,
      2,
      0,
      1,
      0,
      1,
      1,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      2,
      3
    ],
    firstPowers: [
      'Use the powers on the lowest rank green played card',
      'Put 1 pawn from the bank on the left side of your deck',
      'If the highest rank played card is red or yellow, earn 10 gold',
      'Use the powers on the lowest rank yellow played card',
      'If the 2 lowest rank palace cards are the same color, earn the higher rank in coins',
      'Draw 1 for each card in the dungeon',
      'Take 1 of your exiled cards into your hand',
      'If anyone played a card ranked lower than 8, take 1 of your exiled cards back into your hand',
      'If anyone other than you played a green card, take 2 pawns into your hand',
      'Use the powers on the lowest rank non-red played card',
      'Put 1 pawn on the right side of your deck',
      'Use the powers on the lowest rank non-red palace card',
      'Use the powers on the lowest rank yellow palace card',
      'Use the powers on the rightmost non-red card in your deck',
      'Use the powers on the rightmost yellow card in your deck',
      'Pay the rank of the rightmost card in your deck to the bank in coins',
      'Earn 25 gold',
      'If anyone played a card with 1 or more eyes, earn 15 gold',
      'Earn 5 gold for each color on the played cards',
      'If anyone played a yellow card, earn 20 gold',
      'Earn 5 gold for each card in the dungeon',
      'Earn twice the rank of the the biggest card in your deck',
      'Earn the lowest green played rank in coins',
      'If the rightmost card in your deck is green, draw 5',
      'If you have 50 or less gold, draw 5'
    ],
    secondPowers: [
      'Earn 5 gold',
      'Draw the 2 rightmost cards in your deck',
      'Move the leftmost card in your deck to the right side',
      'Earn 1 silver',
      'Swap the leftmost and rightmost cards in your deck',
      'Put 1 pawn from the bank on trial',
      'If your deck is empty, earn 15 gold',
      'Draw the number of colors on the played cards',
      'Draw a number of cards equal to the most eyes on any played card',
      'Use the powers on the lowest rank non-red dungeon card',
      'Draw a number of cards equal to the lowest rank in the dungeon',
      'Use the powers on the highest rank green played card or highest rank green dungeon card, whichever is higher',
      'Use the powers on the highest rank yellow played card or highest rank yellow dungeon card, whichever is higher',
      'Use the powers on the highest rank non-red dungeon card',
      'Use the powers on the lowest rank palace card',
      'Earn 25 gold',
      'Exile 1 card from your hand',
      'If your deck is empty, earn 10 gold',
      'Earn the lowest rank on any yellow played card in coins',
      'Earn 5 gold for each of your exiled cards',
      'Earn the highest rank in the dungeon in coins',
      'Move the biggest card in your deck to the left side',
      'Draw 5',
      'If the lowest or highest rank played card is green, draw 5',
      'If you have 5 or less cards in your deck, draw them all'
    ],
    bonusPowers: [
      'If you have this in play when another player wins the auction, you may take 1 of your exiled cards into your hand',
      '',
      '',
      'If you have this in play during the auction, you may bid silver',
      '',
      '',
      '',
      '',
      '',
      'If you have this in play during the auction, your bid is increased by 10',
      '',
      'If you have this in play when you win an auction, you may take cards from the dungeon as well as the trial',
      'If you have this in play when you win an auction, you may take any of the cards you win directly into your hand',
      'If you have this in play when you win an auction, you may take any number of cards from the dungeon into your hand',
      'If you have this in play when another player wins the auction, you may take any number of your exiled cards into your hand',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ]
  },
  names: {
    archive: 'dungeon',
    archivedTo: 'imprisoned in',
    card: 'card',
    Card: 'Card',
    cards: 'cards',
    Cards: 'Cards',
    center: 'palace',
    charge: 'eye',
    charges: 'eyes',
    deck: 'deck',
    earn: 'earn',
    highestRank: 'highest rank',
    inPlay: 'in play',
    isAddedToMarket: 'is put on trial',
    lowestRank: 'lowest rank',
    major: 'gold',
    market: 'trial',
    minor: 'silver',
    timeDoesNotPass: 'there is no scandal',
    trash: 'exile',
    trashed: 'exiled'
  }
} as const